### ISSUE TITLE
Parse "not determined" Clouds conditions

### ISSUE THREAD

**Issue by xxKRASHxx** [RISCfuture/SwiftMETAR#7]
## Summary

Parsing METARs w\ not determined cloud feature results in a corrupted parsing.

## Expected Behavior
Cloud features such as:
- `BKN013///`
- `//////TCU`

Should:
1) not break parsing;
2) be reflected in a model somehow.

## Current Behavior

All **METAR** features aft go to the RMK property.

## Steps to Reproduce

Parse: 
1. `METAR EGLL 042350Z AUTO 35010KT 320V020 5000 -RADZ BKN008/// OVC015/// //////CB 06/04 Q0993 TEMPO 4000 RADZ`
2. `EGSS 042320Z AUTO 36008KT 4100 -RADZ OVC003/// //////TCU 07/06 Q0992`

_(these are real METAR issues by the authorities)_

**Comment by RISCfuture** [comment]
Resolved with #8
