### ISSUE TITLE
Parse directional visibility

### ISSUE THREAD

**Issue by xxKRASHxx** [RISCfuture/SwiftMETAR#9]
## Summary

Visibility could be provided with Cardinal direction.
Currently, unhandled case.

## Expected Behavior
- `var visibility: Visibility` -> `var visibilities: [Visibility]`
- add direction to the `Visibility`
- add backwards compatible convenience properties

## Current Behavior

Parsing breaks.

## Steps to Reproduce

- Parse examples:
  - `METAR LOWK 042250Z AUTO VRB02KT 9000 3600S BR FEW002 M01/M01 Q1011`
  - ... (provide more?)
- Visibility 3.6km in direction of South does not reflected in parsed structure.

_(these are real METAR issues by the authorities)_

**Comment by RISCfuture** [comment]
Resolved with https://github.com/xxKRASHxx/SwiftMETAR/pull/2
